import { WORLD_SIZE, TILE_SIZE, SPAWN, applyMapData, landmarks, npcs } from './game-data.js';
import { CELL_SIZE, GRID_SIZE, clampMapCenter, findGridPath, isFoliageColor, movementSlices, nearestWalkable } from './navigation.js';
import { removeConnectedBackground } from './sprite-utils.js';

const saveKey = 'lums-quest-v1';
const state = { discovered: new Set(), muted: false, biking: false, started: false, current: null, target: null, scene: null, player: null, keys: null, touch: new Set() };
const mapView = { zoom: 1, x: WORLD_SIZE / 2, y: WORLD_SIZE / 2, overview: null };
const el = (id) => document.getElementById(id), hint = el('hint'), toast = el('toast');
function cameraZoom(scene) { const width=scene.scale.width,height=scene.scale.height,mobile=width<760,portrait=height>width; return (mobile?(portrait?.92:.76):.64)*(state.biking?.72:1); }
function loadSave() { try { const saved = JSON.parse(localStorage.getItem(saveKey)); if (saved?.version === 1) { state.discovered = new Set(saved.discovered || []); state.muted = Boolean(saved.muted); } } catch { localStorage.removeItem(saveKey); } }
function save() { localStorage.setItem(saveKey, JSON.stringify({ version: 1, discovered: [...state.discovered], muted: state.muted })); }
function showToast(message) { toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2600); }
function playTone(frequency = 600, duration = .08) { if (state.muted || !window.AudioContext) return; const context = playTone.context ??= new AudioContext(), osc = context.createOscillator(), gain = context.createGain(); osc.frequency.value = frequency; osc.type = 'square'; gain.gain.setValueAtTime(.04, context.currentTime); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + duration); osc.connect(gain).connect(context.destination); osc.start(); osc.stop(context.currentTime + duration); }
function nearestInteractable() { if (!state.player) return null; const { x, y } = state.player, places = landmarks.map((item) => ({ ...item, kind: 'landmark', distance: Math.hypot(x - item.accessX, y - item.accessY) })).filter((item) => item.distance < 105), people = npcs.map((item) => ({ ...item, kind: 'npc', distance: Math.hypot(x - item.x, y - item.y) })).filter((item) => item.distance < 95); return [...places, ...people].sort((a, b) => a.distance - b.distance)[0] || null; }
function updateHud() { el('dex-count').textContent = `${state.discovered.size}/${landmarks.length}`; el('dex-progress').textContent = `${state.discovered.size} / ${landmarks.length}`; const nearby = nearestInteractable(); state.current = nearby; hint.hidden = !nearby || !state.started; if (nearby) el('hint-text').textContent = nearby.kind === 'npc' ? `TALK: ${nearby.name}` : state.discovered.has(nearby.id) ? `VISIT: ${nearby.shortName}` : `DISCOVER: ${nearby.shortName}`; const closest = landmarks.filter((item) => item.accessX).map((item) => ({ ...item, distance: Math.hypot(state.player.x - item.accessX, state.player.y - item.accessY) })).sort((a, b) => a.distance - b.distance)[0]; el('area-name').textContent = closest?.shortName || 'LUMS CAMPUS'; }
function openDialogue(kicker, title, copy) { el('dialogue-kicker').textContent = kicker; el('dialogue-title').textContent = title; el('dialogue-copy').textContent = copy; el('dialogue-panel').hidden = false; }
function interact() { const item = state.current || nearestInteractable(); if (!item || !state.started) return; if (item.kind === 'npc') { playTone(430, .06); openDialogue(item.name, '“Hey!”', item.line); return; } const fresh = !state.discovered.has(item.id); state.discovered.add(item.id); save(); renderDex(); updateHud(); playTone(fresh ? 720 : 460, fresh ? .15 : .06); openDialogue(fresh ? 'NEW CAMPUSDEX STAMP!' : 'CAMPUSDEX ENTRY', item.name, item.description); if (fresh) showToast(`${item.shortName} added to your CampusDex!`); if (state.target?.id === item.id) state.scene.clearRoute(); }
function renderDex() { el('dex-list').replaceChildren(...landmarks.map((item) => { const known = state.discovered.has(item.id), button = document.createElement('button'); button.className = `dex-entry ${known ? 'known' : ''} ${state.target?.id === item.id ? 'routing' : ''}`; button.innerHTML = `<span class="stamp">${item.letter}</span><span><b>${item.name}</b><small>${known ? item.description : 'Undiscovered · tap to route'}</small></span><i>${state.target?.id === item.id ? '●' : '↗'}</i>`; button.addEventListener('click', () => state.scene?.setRoute(item)); return button; })); el('dex-count').textContent = `${state.discovered.size}/${landmarks.length}`; el('dex-progress').textContent = `${state.discovered.size} / ${landmarks.length}`; }
function mapIsOpen(){return !el('map-panel').hidden;}
function setControlMode(map){el('a-label').textContent=map?'ZOOM +':'ACT';el('b-label').textContent=map?'ZOOM −':'MAP';}
function fullMapTransform(){const canvas=el('full-map'),base=Math.min(canvas.width,canvas.height)/WORLD_SIZE,scale=base*mapView.zoom;return{canvas,scale,originX:canvas.width/2-mapView.x*scale,originY:canvas.height/2-mapView.y*scale};}
function renderFullMap(time=performance.now()){const scene=state.scene;if(!scene?.player||!mapIsOpen())return;const{canvas,scale,originX,originY}=fullMapTransform(),context=canvas.getContext('2d');context.fillStyle='#17293b';context.fillRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=false;context.drawImage(mapView.overview,originX,originY,WORLD_SIZE*scale,WORLD_SIZE*scale);if(scene.routePath?.length){context.strokeStyle='#17293bcc';context.lineWidth=12;context.beginPath();context.moveTo(originX+scene.player.x*scale,originY+scene.player.y*scale);scene.routePath.slice(1).forEach(([x,y])=>context.lineTo(originX+x*scale,originY+y*scale));context.stroke();context.strokeStyle='#ffe047';context.lineWidth=5;context.stroke();}context.textAlign='center';context.textBaseline='middle';const fontSize=Math.max(9,9*Math.sqrt(mapView.zoom));context.font=`${fontSize}px "Press Start 2P"`;landmarks.forEach((item)=>{const [x,y]=item.labels[0],px=originX+x*scale,py=originY+y*scale,text=item.shortName;if(px<0||py<0||px>canvas.width||py>canvas.height)return;const width=context.measureText(text).width+10;context.fillStyle='#17293bde';context.fillRect(px-width/2,py-fontSize,width,fontSize*2);context.fillStyle='#fff6d9';context.fillText(text,px,py);});if(state.target){const x=originX+state.target.accessX*scale,y=originY+state.target.accessY*scale;context.strokeStyle='#fff';context.lineWidth=5;context.fillStyle='#ffe047';context.beginPath();context.moveTo(x,y-18);context.lineTo(x+14,y);context.lineTo(x,y+18);context.lineTo(x-14,y);context.closePath();context.fill();context.stroke();}const x=originX+scene.player.x*scale,y=originY+scene.player.y*scale,pulse=14+Math.sin(time/180)*3;context.fillStyle='#fff';context.beginPath();context.arc(x,y,pulse+5,0,Math.PI*2);context.fill();context.fillStyle='#f06955';context.beginPath();context.arc(x,y,pulse,0,Math.PI*2);context.fill();context.fillStyle='#17293b';context.font='11px "Press Start 2P"';context.fillText('YOU',x,y-28);}
function resizeFullMap(){const canvas=el('full-map'),ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(canvas.clientWidth*ratio));canvas.height=Math.max(1,Math.round(canvas.clientHeight*ratio));renderFullMap();}
function zoomFullMap(multiplier){mapView.zoom=Math.max(1,Math.min(4,mapView.zoom*multiplier));renderFullMap();playTone(multiplier>1?680:440,.04);}
function panFullMap(dx,dy,delta){const canvas=el('full-map'),base=Math.min(canvas.width,canvas.height)/WORLD_SIZE,halfX=canvas.width/(2*base*mapView.zoom),halfY=canvas.height/(2*base*mapView.zoom),step=1400*delta/1000/mapView.zoom;mapView.x=clampMapCenter(mapView.x+dx*step,halfX,WORLD_SIZE);mapView.y=clampMapCenter(mapView.y+dy*step,halfY,WORLD_SIZE);}
function openFullMap(){const scene=state.scene;if(!scene?.player)return;closePanels();if(!mapView.overview){mapView.overview=document.createElement('canvas');mapView.overview.width=mapView.overview.height=1024;const context=mapView.overview.getContext('2d');scene.cache.json.get('map-data').tiles.forEach((tile)=>context.drawImage(scene.textures.get(tile.id).getSourceImage(),tile.global_offset[0]/8,tile.global_offset[1]/8,TILE_SIZE/8,TILE_SIZE/8));}mapView.zoom=1;mapView.x=mapView.y=WORLD_SIZE/2;el('map-panel').hidden=false;document.body.classList.add('map-open');setControlMode(true);resizeFullMap();playTone(560,.06);}
function setMapWaypoint(event){if(!mapIsOpen())return;const{canvas,scale,originX,originY}=fullMapTransform(),rect=canvas.getBoundingClientRect(),px=(event.clientX-rect.left)*canvas.width/rect.width,py=(event.clientY-rect.top)*canvas.height/rect.height,x=(px-originX)/scale,y=(py-originY)/scale;if(x<0||y<0||x>WORLD_SIZE||y>WORLD_SIZE)return;state.scene.setWaypoint(x,y);renderFullMap();}
function drawPerson(scene, key, shirt, skin, hair, player = false) { const g = scene.make.graphics({ add: false }); g.fillStyle(0x101923).fillEllipse(2, 43, 34, 8); g.fillStyle(hair).fillRect(7, 1, 21, 8).fillRect(4, 7, 27, 8); g.fillStyle(skin).fillRect(7, 12, 21, 14); g.fillStyle(0x17293b).fillRect(10, 17, 3, 3).fillRect(22, 17, 3, 3); g.fillStyle(shirt).fillRect(5, 26, 25, 16); g.fillStyle(player ? 0xf06c52 : 0xf5e5c0).fillRect(15, 29, 6, 10); g.fillStyle(0x27354d).fillRect(7, 40, 8, 8).fillRect(21, 40, 8, 8); if (player) g.fillStyle(0xffd858).fillRect(3, 28, 5, 12).fillRect(28, 28, 5, 12); g.generateTexture(key, 36, 48); g.destroy(); }
function createPlayerSprites(scene) {
  const source = scene.textures.get('player-source').getSourceImage(), sheet = document.createElement('canvas'); sheet.width = 48; sheet.height = 96; const context = sheet.getContext('2d', { willReadFrequently: true }); context.imageSmoothingEnabled = false;
  const sourceRows = [42, 76, 110], sourceColumns = [8, 25, 42]; sourceRows.forEach((sourceY, row) => sourceColumns.forEach((sourceX, column) => context.drawImage(source, sourceX, sourceY, 16, 32, column * 16, row * 32, 16, 32)));
  for (let row = 0; row < 3; row += 1) for (let column = 0; column < 3; column += 1) { const frame = context.getImageData(column * 16, row * 32, 16, 32); removeConnectedBackground(frame.data, 16, 32); context.putImageData(frame, column * 16, row * 32); } const texture = scene.textures.addCanvas('player-sheet', sheet);
  ['down', 'up', 'side'].forEach((direction, row) => [0, 1, 2].forEach((frame) => texture.add(`${direction}-${frame}`, 0, frame * 16, row * 32, 16, 32)));
  ['down', 'up', 'side'].forEach((direction) => scene.anims.create({ key: `walk-${direction}`, frames: [0, 1, 2].map((frame) => ({ key: 'player-sheet', frame: `${direction}-${frame}` })), frameRate: 8, repeat: -1 }));
  const bikeSheet=document.createElement('canvas');bikeSheet.width=96;bikeSheet.height=128;const bikeContext=bikeSheet.getContext('2d',{willReadFrequently:true});bikeContext.imageSmoothingEnabled=false;const bikeRows=[42,76,110,144],bikeColumns=[128,162,196];bikeRows.forEach((sourceY,row)=>bikeColumns.forEach((sourceX,column)=>bikeContext.drawImage(source,sourceX,sourceY,32,32,column*32,row*32,32,32)));for(let row=0;row<4;row+=1)for(let column=0;column<3;column+=1){const frame=bikeContext.getImageData(column*32,row*32,32,32);removeConnectedBackground(frame.data,32,32);bikeContext.putImageData(frame,column*32,row*32);}const bikeTexture=scene.textures.addCanvas('bike-sheet',bikeSheet);['down','up','left','right'].forEach((direction,row)=>[0,1,2].forEach((frame)=>bikeTexture.add(`${direction}-${frame}`,0,frame*32,row*32,32,32)));['down','up','left','right'].forEach((direction)=>scene.anims.create({key:`bike-${direction}`,frames:[0,1,2].map((frame)=>({key:'bike-sheet',frame:`${direction}-${frame}`})),frameRate:12,repeat:-1}));
}

class CampusScene extends Phaser.Scene {
  constructor() { super('campus'); }
  preload() { ['r1_c1', 'r1_c2', 'r2_c1', 'r2_c2'].forEach((tile) => this.load.image(tile, `assets/pixel_map/${tile}.png`)); this.load.json('map-data', 'assets/pixel_map/master.json'); this.load.image('player-source', 'assets/Game Boy Advance - Pokemon FireRed _ LeafGreen - Playable Characters - Player Sprites.png'); }
  create() {
    const mapData = this.cache.json.get('map-data'); applyMapData(mapData); renderDex(); mapData.tiles.forEach((tile) => this.add.image(...tile.global_offset, tile.id).setOrigin(0).setDisplaySize(TILE_SIZE, TILE_SIZE).setDepth(0)); this.buildWalkability(mapData);
    this.routeUnderlay = this.add.graphics().setDepth(4); this.routeLine = this.add.graphics().setDepth(5); this.targetMarker = this.add.graphics().setDepth(8); const labels = [];
    landmarks.forEach((item) => {
      const access = this.nearestWorld(item.x, item.y); item.accessIndex = access.index; item.accessX = access.x; item.accessY = access.y;
      item.labels.forEach(([x, y]) => { const label = this.add.text(x, y, `${item.letter} · ${item.shortName}`, { fontFamily: '"Press Start 2P"', fontSize: '15px', color: '#fff8d8', backgroundColor: '#17293be8', padding: { x: 8, y: 6 }, stroke: '#17293b', strokeThickness: 2 }).setOrigin(.5).setDepth(41); labels.push(label); });
      const marker = this.add.circle(item.accessX, item.accessY - 18, 7, 0xffe470).setDepth(40); this.tweens.add({ targets: marker, alpha: .25, scale: 1.7, duration: 650, yoyo: true, repeat: -1 });
    });
    createPlayerSprites(this); const spawn = this.nearestWorld(SPAWN.x, SPAWN.y); this.playerShadow = this.add.ellipse(spawn.x, spawn.y + 35, 60, 17, 0x101b2a, .35).setDepth(17); this.player = this.add.sprite(spawn.x, spawn.y, 'player-sheet', 'down-1').setScale(3.2).setDepth(20); this.playerDot = this.add.circle(spawn.x, spawn.y, 26, 0x75deef, .25).setStrokeStyle(6, 0xffffff, .9).setDepth(18);
    npcs.forEach((npc, index) => { const point = this.nearestWorld(...npc.near); npc.x = point.x; npc.y = point.y; drawPerson(this, `npc-${index}`, npc.color, npc.skin, npc.hair); const sprite = this.add.sprite(npc.x + 38, npc.y - 12, `npc-${index}`).setScale(1.9).setDepth(19); this.tweens.add({ targets: sprite, y: sprite.y - 5, duration: 720 + index * 40, yoyo: true, repeat: -1, ease: 'Sine.easeInOut' }); const mark = this.add.text(sprite.x, sprite.y - 53, '!', { fontFamily: '"Press Start 2P"', fontSize: '18px', color: '#fff7ba', stroke: '#192c3d', strokeThickness: 6 }).setOrigin(.5).setDepth(20); this.tweens.add({ targets: mark, y: mark.y - 4, duration: 520, yoyo: true, repeat: -1 }); });
    this.add.image(0, 0, 'canopy-overlay').setOrigin(0).setDisplaySize(WORLD_SIZE, WORLD_SIZE).setDepth(30);
    this.cameras.main.setBounds(0, 0, WORLD_SIZE, WORLD_SIZE).startFollow(this.player, true, .16, .16).setRoundPixels(true).ignore(this.playerDot); this.mini = this.cameras.add().setName('minimap').setBackgroundColor(0x17293b).startFollow(this.player, true, 1, 1).setRoundPixels(true); this.mini.ignore(labels);
    state.scene = this; state.player = this.player; state.keys = this.input.keyboard.addKeys({ up: 'UP', down: 'DOWN', left: 'LEFT', right: 'RIGHT', w: 'W', a: 'A', s: 'S', d: 'D' }); this.layout(); this.scale.on('resize', () => this.layout());
    this.input.keyboard.on('keydown-E', interact); this.input.keyboard.on('keydown-M', () => this.openDex()); this.input.keyboard.on('keydown-ESC', closePanels); this.input.keyboard.on('keydown-SPACE', interact);
  }
  buildWalkability(data) {
    this.walkable = new Uint8Array(GRID_SIZE * GRID_SIZE); data.walkability.rows.forEach((runs,y)=>runs.forEach(([x,length])=>this.walkable.fill(1,y*GRID_SIZE+x,y*GRID_SIZE+x+length)));
    const canopy = document.createElement('canvas'); canopy.width = canopy.height = GRID_SIZE; const canopyContext = canopy.getContext('2d'); data.tiles.forEach((tile) => canopyContext.drawImage(this.textures.get(tile.id).getSourceImage(), tile.global_offset[0] / CELL_SIZE, tile.global_offset[1] / CELL_SIZE, TILE_SIZE / CELL_SIZE, TILE_SIZE / CELL_SIZE)); canopyContext.globalCompositeOperation = 'destination-in'; canopyContext.scale(1 / CELL_SIZE, 1 / CELL_SIZE);
    canopyContext.setTransform(1,0,0,1,0,0); const image=canopyContext.getImageData(0,0,GRID_SIZE,GRID_SIZE); for(let index=0;index<GRID_SIZE*GRID_SIZE;index++){const pixel=index*4;if(!isFoliageColor(image.data[pixel],image.data[pixel+1],image.data[pixel+2]))image.data[pixel+3]=0;} canopyContext.globalCompositeOperation='source-over'; canopyContext.putImageData(image,0,0); this.textures.addCanvas('canopy-overlay', canopy);
  }
  nearestWorld(x, y) { const index = nearestWalkable(this.walkable, GRID_SIZE, Math.floor(x / CELL_SIZE), Math.floor(y / CELL_SIZE)); return { index, x: (index % GRID_SIZE) * CELL_SIZE + CELL_SIZE / 2, y: Math.floor(index / GRID_SIZE) * CELL_SIZE + CELL_SIZE / 2 }; }
  canStand(x, y) { const gridX = Math.floor(x / CELL_SIZE), gridY = Math.floor(y / CELL_SIZE); return gridX >= 0 && gridY >= 0 && gridX < GRID_SIZE && gridY < GRID_SIZE && Boolean(this.walkable[gridY * GRID_SIZE + gridX]); }
  openDex() { el('dex-panel').hidden = false; renderDex(); }
  drawRoute() {
    if(!this.routePath?.length)return;const points=[[this.player.x,this.player.y],...this.routePath.slice(1)];this.routeUnderlay.clear().lineStyle(25,0x17293b,.72).beginPath().moveTo(...points[0]);points.slice(1).forEach(([x,y])=>this.routeUnderlay.lineTo(x,y));this.routeUnderlay.strokePath();this.routeLine.clear().lineStyle(10,0xffdb4d,1).beginPath().moveTo(...points[0]);points.slice(1).forEach(([x,y])=>this.routeLine.lineTo(x,y));this.routeLine.strokePath();
  }
  setRoute(item,silent=false) {
    if(item.accessIndex==null){const access=this.nearestWorld(item.x,item.y);item.accessIndex=access.index;item.accessX=access.x;item.accessY=access.y;}const start=this.nearestWorld(this.player.x,this.player.y).index,path=findGridPath(this.walkable,GRID_SIZE,start,item.accessIndex);if(!path.length){if(!silent)showToast('No walkable route found.');return;}this.routePath=path.map((index)=>[(index%GRID_SIZE)*CELL_SIZE+4,Math.floor(index/GRID_SIZE)*CELL_SIZE+4]);this.routeOrigin={x:this.player.x,y:this.player.y};this.lastReroute=performance.now();this.drawRoute();this.targetMarker.clear().lineStyle(8,0xffffff,1).strokeCircle(item.accessX,item.accessY,36).fillStyle(0xf06955,.95).fillCircle(item.accessX,item.accessY,23);state.target=item;if(!silent){el('route-name').textContent=item.shortName;el('route-chip').hidden=false;el('dex-panel').hidden=true;renderDex();showToast(`Route set: ${item.name}`);playTone(590,.08);}
  }
  setWaypoint(x,y) { const access=this.nearestWorld(x,y),waypoint={id:'custom-waypoint',name:'Custom waypoint',shortName:'WAYPOINT',x,y,accessIndex:access.index,accessX:access.x,accessY:access.y};this.setRoute(waypoint); }
  refreshRoute(time) { if(!state.target)return;if(Math.hypot(this.player.x-state.target.accessX,this.player.y-state.target.accessY)<55){showToast('You have arrived!');playTone(760,.12);this.clearRoute();return;}if(time-this.lastReroute>650&&Math.hypot(this.player.x-this.routeOrigin.x,this.player.y-this.routeOrigin.y)>64)this.setRoute(state.target,true);else this.drawRoute(); }
  clearRoute() { this.routeUnderlay.clear(); this.routeLine.clear(); this.targetMarker.clear(); this.routePath=null; state.target = null; el('route-chip').hidden = true; renderDex(); }
  layout() {
    const width = this.scale.width, height = this.scale.height, mobile = width < 760; this.cameras.main.setZoom(cameraZoom(this));
    const size = mobile ? Math.min(174, width * .44) : 240, x = mobile ? width - size - 12 : 24, y = mobile ? 66 : height - size - 24; this.mini.setViewport(x, y, size, size).setZoom(mobile ? .18 : .16);
    this.miniMaskGraphic?.destroy(); this.miniMaskGraphic = this.make.graphics({ add: false }).fillStyle(0xffffff).fillCircle(x + size / 2, y + size / 2, size / 2 - 4); this.mini.setMask(this.miniMaskGraphic.createGeometryMask()); document.documentElement.style.setProperty('--mini-x', `${x}px`); document.documentElement.style.setProperty('--mini-y', `${y}px`); document.documentElement.style.setProperty('--mini-size', `${size}px`); document.documentElement.style.setProperty('--route-y', `${mobile ? y + size + 8 : y - 58}px`);
  }
  update(time, delta) {
    if (!state.started || !this.player) return; const k = state.keys, left = k.left.isDown || k.a.isDown || state.touch.has('left'), right = k.right.isDown || k.d.isDown || state.touch.has('right'), up = k.up.isDown || k.w.isDown || state.touch.has('up'), down = k.down.isDown || k.s.isDown || state.touch.has('down'); let dx = (right ? 1 : 0) - (left ? 1 : 0), dy = (down ? 1 : 0) - (up ? 1 : 0); if (dx && dy) { dx *= .707; dy *= .707; }
    if(mapIsOpen()){panFullMap(dx,dy,Math.min(delta,40));renderFullMap(time);return;}
    const step = (state.biking ? 600 : 300) * Math.min(delta, 40) / 1000, slices = movementSlices(step); for (let slice=0;slice<slices;slice+=1) { const targetX = this.player.x + dx * step/slices, targetY = this.player.y + dy * step/slices; if (this.canStand(targetX, targetY)) this.player.setPosition(targetX, targetY); else if (this.canStand(targetX, this.player.y)) this.player.x = targetX; else if (this.canStand(this.player.x, targetY)) this.player.y = targetY; }
    if (dx || dy) { const direction = Math.abs(dx) > Math.abs(dy) ? (state.biking ? (dx < 0 ? 'left' : 'right') : 'side') : dy < 0 ? 'up' : 'down'; this.player.setFlipX(!state.biking && direction === 'side' && dx > 0); this.player.anims.play(`${state.biking ? 'bike' : 'walk'}-${direction}`, true); } else this.player.anims.stop(); this.playerShadow.setPosition(this.player.x, this.player.y + 52); this.playerDot.setPosition(this.player.x, this.player.y); this.refreshRoute(time); updateHud();
  }
}
function closePanels() { document.querySelectorAll('.panel').forEach((panel) => { panel.hidden = true; }); document.body.classList.remove('map-open'); setControlMode(false); }
function boot() { loadSave(); renderDex(); el('sound-button').textContent = state.muted ? '×' : '♫'; new Phaser.Game({ type: Phaser.AUTO, parent: 'game', width: window.innerWidth, height: window.innerHeight, backgroundColor: '#68b733', pixelArt: true, scale: { mode: Phaser.Scale.RESIZE }, scene: CampusScene }); }
el('start-button').addEventListener('click', () => { state.started = true; el('start-screen').hidden = true; playTone(520, .12); showToast('Tap B for CampusDex or start exploring!'); }); el('dex-button').addEventListener('click', () => state.scene?.openDex()); el('map-button').addEventListener('click', () => mapIsOpen()?zoomFullMap(.8):state.scene?.openDex()); el('sound-button').addEventListener('click', () => { state.muted = !state.muted; el('sound-button').textContent = state.muted ? '×' : '♫'; save(); }); el('action-button').addEventListener('click', () => mapIsOpen()?zoomFullMap(1.25):interact()); el('clear-route').addEventListener('click', () => state.scene?.clearRoute()); document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => { el(button.dataset.close).hidden = true; if(button.dataset.close==='map-panel'){document.body.classList.remove('map-open');setControlMode(false);} }));
el('bike-button').addEventListener('click', () => { state.biking = !state.biking; el('bike-button').setAttribute('aria-pressed', state.biking); el('bike-button').textContent = state.biking ? 'WALK' : 'BIKE'; if(state.scene){state.scene.cameras.main.zoomTo(cameraZoom(state.scene),280,'Sine.easeOut');state.player.setFlipX(false).setTexture(state.biking?'bike-sheet':'player-sheet','down-1');} showToast(state.biking?'Bike mode: faster travel!':'Walking mode'); playTone(state.biking?700:480,.08); });
el('minimap-button').addEventListener('click',openFullMap);
el('full-map').addEventListener('pointerup',setMapWaypoint);
window.addEventListener('resize',()=>{if(mapIsOpen())resizeFullMap();});
const touchPointers=new Map(),syncTouch=()=>{state.touch.clear();touchPointers.forEach((direction)=>{if(direction)state.touch.add(direction);});document.querySelectorAll('[data-direction]').forEach((button)=>button.classList.toggle('pressed',state.touch.has(button.dataset.direction)));};document.querySelectorAll('[data-direction]').forEach((button)=>{button.addEventListener('pointerdown',(event)=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);touchPointers.set(event.pointerId,button.dataset.direction);syncTouch();navigator.vibrate?.(8);});button.addEventListener('pointermove',(event)=>{if(!touchPointers.has(event.pointerId))return;const next=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('[data-direction]');touchPointers.set(event.pointerId,next?.dataset.direction||null);syncTouch();});['pointerup','pointercancel','lostpointercapture'].forEach((name)=>button.addEventListener(name,(event)=>{touchPointers.delete(event.pointerId);syncTouch();}));});document.querySelectorAll('.game-button').forEach((button)=>{button.addEventListener('pointerdown',()=>{button.classList.add('pressed');navigator.vibrate?.(10);});['pointerup','pointercancel','pointerleave'].forEach((name)=>button.addEventListener(name,()=>button.classList.remove('pressed')));});const clearTouch=()=>{touchPointers.clear();state.touch.clear();document.querySelectorAll('.pressed').forEach((button)=>button.classList.remove('pressed'));};window.addEventListener('blur',clearTouch);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTouch();});document.querySelector('.mobile-controls').addEventListener('contextmenu',(event)=>event.preventDefault());
boot();
