import { WORLD_SIZE, TILE_SIZE, SPAWN, applyMapData, landmarks, npcs, validGender, validSavedPosition } from './game-data.js';
import { CELL_SIZE, GRID_SIZE, clampMapCenter, distanceToPath, findGridPath, movementSlices, nearestWalkable, trimPathToPlayer } from './navigation.js';
import { removeSpriteSheetBackground } from './sprite-utils.js';

const saveKey = 'lums-quest-v1';
const state = { discovered: new Set(), muted: false, biking: false, profiled: false, email: '', gender: 'male', updatedAt: '', savedPosition: null, started: false, startRequested: false, current: null, target: null, scene: null, player: null, keys: null, touch: new Set() };
const mapView = { zoom: 1, x: WORLD_SIZE / 2, y: WORLD_SIZE / 2, overview: null };
const el = (id) => document.getElementById(id), hint = el('hint'), toast = el('toast');
const apiBase = document.querySelector('meta[name="golums-api-url"]')?.content.replace(/\/$/, '');
const tutorialSteps = [
  { kicker:'WELCOME TO LUMS', title:'You’re at In Gate', copy:'This is the main campus entrance—and the start of your adventure. Explore the real map and collect every landmark.', target:'.area-chip' },
  { kicker:'MOVE AROUND', title:'Take your first steps', copy:'Use WASD or the arrow keys. On mobile, use the D-pad. You can keep moving while this guide is open.', target:()=>matchMedia('(pointer:coarse), (max-width:760px)').matches?'.mobile-controls':'#game' },
  { kicker:'MEET & DISCOVER', title:'Look for glowing markers', copy:'Walk close to a person or landmark, then press E or Space. On mobile, tap A. New places become CampusDex stamps.', target:()=>matchMedia('(pointer:coarse), (max-width:760px)').matches?'#action-button':'#game' },
  { kicker:'FIND YOUR WAY', title:'CampusDex draws routes', copy:'Open CampusDex, choose any place, and follow the yellow route from where you are now. Press M on a keyboard or B on mobile.', target:()=>matchMedia('(pointer:coarse), (max-width:760px)').matches?'#map-button':'#dex-button' },
  { kicker:'SEE THE CAMPUS', title:'Your minimap keeps you oriented', copy:'Tap the round minimap for the full campus map. Tap anywhere on it to set your own waypoint.', target:'#minimap-button' },
  { kicker:'READY TO EXPLORE', title:'Walk—or ride', copy:'The bike is faster for long trips. Your position, discoveries, character, and settings save automatically.', target:'#bike-button' },
];
let tutorialStep = -1;
const tutorialKey = () => `go-lums-tutorial:${state.email}`;
function showTutorialStep(index) { document.querySelector('.tutorial-focus')?.classList.remove('tutorial-focus');if(index>=tutorialSteps.length)return finishTutorial();tutorialStep=index;const step=tutorialSteps[index],target=document.querySelector(typeof step.target==='function'?step.target():step.target);target?.classList.add('tutorial-focus');el('tutorial-kicker').textContent=step.kicker;el('tutorial-title').textContent=step.title;el('tutorial-copy').textContent=step.copy;el('tutorial-progress').innerHTML=tutorialSteps.map((_,i)=>`<i class="${i===index?'current':''}"></i>`).join('');el('tutorial-next').innerHTML=index===tutorialSteps.length-1?'LET’S GO! <span>→</span>':'NEXT <span>→</span>';el('tutorial').hidden=false; }
function finishTutorial() { document.querySelector('.tutorial-focus')?.classList.remove('tutorial-focus');el('tutorial').hidden=true;tutorialStep=-1;if(state.email)localStorage.setItem(tutorialKey(),'done');showToast('Adventure started—discover your first landmark!'); }
function startTutorial(force=false) { if(!state.started||(!force&&localStorage.getItem(tutorialKey())))return;closePanels();showTutorialStep(0); }
function cameraZoom(scene) { const width=scene.scale.width,height=scene.scale.height,mobile=width<760,portrait=height>width; return (mobile?(portrait?.92:.76):.64)*(state.biking?.72:1); }
function loadSave() { try { const saved = JSON.parse(localStorage.getItem(saveKey)); if ([1,2,3,4,5,6,7].includes(saved?.version)) { state.discovered = new Set(Array.isArray(saved.discovered)?saved.discovered:[]); state.muted=Boolean(saved.muted);state.biking=Boolean(saved.biking);state.email=typeof saved.email==='string'?saved.email:'';state.updatedAt=saved.updatedAt||'';if(validSavedPosition(saved.position))state.savedPosition=saved.position;if(validGender(saved.gender))state.gender=saved.gender;state.profiled=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.email)&&validGender(state.gender); } } catch (error) { console.warn('Could not load local progress.', error); } }
function progressPayload() { const position=state.player?[state.player.x,state.player.y]:state.savedPosition;return position&&state.profiled?{email:state.email,gender:state.gender,discovered:[...state.discovered],position,muted:state.muted,biking:state.biking,updatedAt:state.updatedAt}:null; }
function scheduleRemoteSave() { if(!apiBase||!progressPayload())return;clearTimeout(scheduleRemoteSave.timer);scheduleRemoteSave.timer=setTimeout(async()=>{try{await fetch(`${apiBase}/api/progress`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(progressPayload())});}catch(error){console.warn('Remote progress sync failed; local progress is safe.',error);}},1000); }
function save(remote=true) { try { const position=state.player?[state.player.x,state.player.y]:state.savedPosition;if(position)state.savedPosition=position;state.updatedAt=new Date().toISOString();localStorage.setItem(saveKey,JSON.stringify({version:7,discovered:[...state.discovered],muted:state.muted,biking:state.biking,profiled:state.profiled,email:state.email,gender:state.gender,updatedAt:state.updatedAt,position}));if(remote)scheduleRemoteSave(); } catch (error) { console.warn('Could not save local progress.', error); } }
async function syncRemote() { if(!apiBase||!state.profiled)return;try{const response=await fetch(`${apiBase}/api/progress/load`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:state.email})});if(response.status===404){save();return;}if(!response.ok)throw new Error(`HTTP ${response.status}`);const remote=await response.json();if(Date.parse(remote.updatedAt)<=Date.parse(state.updatedAt||0))return scheduleRemoteSave();state.discovered=new Set(remote.discovered);state.gender=remote.gender;state.muted=remote.muted;state.biking=remote.biking;state.savedPosition=remote.position;state.updatedAt=remote.updatedAt;state.player?.setPosition(...remote.position).setTexture(remote.biking?`bike-${remote.gender}`:`player-${remote.gender}`,'down-1');el('profile-screen').hidden=true;save(false);renderDex();updateHud();showToast('Cloud progress restored.');}catch(error){if(!state.updatedAt)save();console.warn('Remote progress unavailable; using local progress.',error);} }
function showToast(message) { toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2600); }
function playTone(frequency = 600, duration = .08) { if (state.muted || !window.AudioContext) return; const context = playTone.context ??= new AudioContext(), osc = context.createOscillator(), gain = context.createGain(); osc.frequency.value = frequency; osc.type = 'square'; gain.gain.setValueAtTime(.04, context.currentTime); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + duration); osc.connect(gain).connect(context.destination); osc.start(); osc.stop(context.currentTime + duration); }
function gameShortcut(action) { return () => { if (state.started && !document.activeElement?.matches('input,textarea,select,[contenteditable]') && !document.querySelector('dialog[open]')) action(); }; }
function nearestInteractable() { if (!state.player) return null; const { x, y } = state.player, places = landmarks.map((item) => ({ ...item, kind: 'landmark', distance: Math.hypot(x - item.accessX, y - item.accessY) })).filter((item) => item.distance < 105), people = npcs.map((item) => ({ ...item, kind: 'npc', distance: Math.hypot(x - item.x, y - item.y) })).filter((item) => item.distance < 95); return [...places, ...people].sort((a, b) => a.distance - b.distance)[0] || null; }
function updateHud() { el('dex-count').textContent = `${state.discovered.size}/${landmarks.length}`; el('dex-progress').textContent = `${state.discovered.size} / ${landmarks.length}`; const nearby = nearestInteractable(); state.current = nearby; hint.hidden = !nearby || !state.started; if (nearby) el('hint-text').textContent = nearby.kind === 'npc' ? `TALK: ${nearby.name}` : state.discovered.has(nearby.id) ? `VISIT: ${nearby.shortName}` : `DISCOVER: ${nearby.shortName}`; const closest = landmarks.filter((item) => item.accessX).map((item) => ({ ...item, distance: Math.hypot(state.player.x - item.accessX, state.player.y - item.accessY) })).sort((a, b) => a.distance - b.distance)[0]; el('area-name').textContent = closest?.shortName || 'LUMS CAMPUS'; }
function openPanel(id) { const panel=el(id);if(!panel.open)panel.showModal();panel.querySelector('button')?.focus(); }
function openDialogue(kicker, title, copy) { el('dialogue-kicker').textContent = kicker; el('dialogue-title').textContent = title; el('dialogue-copy').textContent = copy; openPanel('dialogue-panel'); }
function interact() { const item = state.current || nearestInteractable(); if (!item || !state.started) return; if (item.kind === 'npc') { playTone(430, .06); openDialogue(item.name, '“Hey!”', item.line); return; } const fresh = !state.discovered.has(item.id); state.discovered.add(item.id); save(); renderDex(); updateHud(); playTone(fresh ? 720 : 460, fresh ? .15 : .06); openDialogue(fresh ? 'NEW CAMPUSDEX STAMP!' : 'CAMPUSDEX ENTRY', item.name, item.description); if (fresh) showToast(`${item.shortName} added to your CampusDex!`); if (state.target?.id === item.id) state.scene.clearRoute(); }
function renderDex() { el('dex-list').replaceChildren(...landmarks.map((item) => { const known = state.discovered.has(item.id), button = document.createElement('button'); button.className = `dex-entry ${known ? 'known' : ''} ${state.target?.id === item.id ? 'routing' : ''}`; button.innerHTML = `<span class="stamp">${item.letter}</span><span><b>${item.name}</b><small>${known ? item.description : 'Undiscovered · tap to route'}</small></span><i>${state.target?.id === item.id ? '●' : '↗'}</i>`; button.addEventListener('click', () => state.scene?.setRoute(item)); return button; })); el('dex-count').textContent = `${state.discovered.size}/${landmarks.length}`; el('dex-progress').textContent = `${state.discovered.size} / ${landmarks.length}`; }
function mapIsOpen(){return el('map-panel').open;}
function setControlMode(map){el('a-label').textContent=map?'ZOOM +':'ACT';el('b-label').textContent=map?'ZOOM −':'MAP';}
function fullMapTransform(){const canvas=el('full-map'),base=Math.min(canvas.width,canvas.height)/WORLD_SIZE,scale=base*mapView.zoom;return{canvas,scale,originX:canvas.width/2-mapView.x*scale,originY:canvas.height/2-mapView.y*scale};}
function renderFullMap(time=performance.now()){const scene=state.scene;if(!scene?.player||!mapIsOpen())return;const{canvas,scale,originX,originY}=fullMapTransform(),context=canvas.getContext('2d');context.fillStyle='#17293b';context.fillRect(0,0,canvas.width,canvas.height);context.imageSmoothingEnabled=false;context.drawImage(mapView.overview,originX,originY,WORLD_SIZE*scale,WORLD_SIZE*scale);if(scene.routePath?.length){context.strokeStyle='#17293bcc';context.lineWidth=12;context.beginPath();context.moveTo(originX+scene.player.x*scale,originY+scene.player.y*scale);scene.routePath.forEach(([x,y])=>context.lineTo(originX+x*scale,originY+y*scale));context.stroke();context.strokeStyle='#ffe047';context.lineWidth=5;context.stroke();}context.textAlign='center';context.textBaseline='middle';const fontSize=Math.max(9,9*Math.sqrt(mapView.zoom));context.font=`${fontSize}px "Press Start 2P"`;landmarks.forEach((item)=>{const [x,y]=item.labels[0],px=originX+x*scale,py=originY+y*scale,text=item.shortName;if(px<0||py<0||px>canvas.width||py>canvas.height)return;const width=context.measureText(text).width+10;context.fillStyle='#17293bde';context.fillRect(px-width/2,py-fontSize,width,fontSize*2);context.fillStyle='#fff6d9';context.fillText(text,px,py);});if(state.target){const x=originX+state.target.accessX*scale,y=originY+state.target.accessY*scale;context.strokeStyle='#fff';context.lineWidth=5;context.fillStyle='#ffe047';context.beginPath();context.moveTo(x,y-18);context.lineTo(x+14,y);context.lineTo(x,y+18);context.lineTo(x-14,y);context.closePath();context.fill();context.stroke();}const x=originX+scene.player.x*scale,y=originY+scene.player.y*scale,pulse=14+Math.sin(time/180)*3;context.fillStyle='#fff';context.beginPath();context.arc(x,y,pulse+5,0,Math.PI*2);context.fill();context.fillStyle='#f06955';context.beginPath();context.arc(x,y,pulse,0,Math.PI*2);context.fill();context.fillStyle='#17293b';context.font='11px "Press Start 2P"';context.fillText('YOU',x,y-28);}
function resizeFullMap(){const canvas=el('full-map'),ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(canvas.clientWidth*ratio));canvas.height=Math.max(1,Math.round(canvas.clientHeight*ratio));renderFullMap();}
function zoomFullMap(multiplier){mapView.zoom=Math.max(1,Math.min(4,mapView.zoom*multiplier));renderFullMap();playTone(multiplier>1?680:440,.04);}
function panFullMap(dx,dy,delta){const canvas=el('full-map'),base=Math.min(canvas.width,canvas.height)/WORLD_SIZE,halfX=canvas.width/(2*base*mapView.zoom),halfY=canvas.height/(2*base*mapView.zoom),step=1400*delta/1000/mapView.zoom;mapView.x=clampMapCenter(mapView.x+dx*step,halfX,WORLD_SIZE);mapView.y=clampMapCenter(mapView.y+dy*step,halfY,WORLD_SIZE);}
function openFullMap(){const scene=state.scene;if(!scene?.player)return;closePanels();if(!mapView.overview){mapView.overview=document.createElement('canvas');mapView.overview.width=mapView.overview.height=1024;const context=mapView.overview.getContext('2d');scene.cache.json.get('map-data').tiles.forEach((tile)=>context.drawImage(scene.textures.get(tile.id).getSourceImage(),tile.global_offset[0]/8,tile.global_offset[1]/8,TILE_SIZE/8,TILE_SIZE/8));}mapView.zoom=1;mapView.x=mapView.y=WORLD_SIZE/2;openPanel('map-panel');document.body.classList.add('map-open');setControlMode(true);resizeFullMap();playTone(560,.06);}
function setMapWaypoint(event){if(!mapIsOpen())return;const{canvas,scale,originX,originY}=fullMapTransform(),rect=canvas.getBoundingClientRect(),px=(event.clientX-rect.left)*canvas.width/rect.width,py=(event.clientY-rect.top)*canvas.height/rect.height,x=(px-originX)/scale,y=(py-originY)/scale;if(x<0||y<0||x>WORLD_SIZE||y>WORLD_SIZE)return;state.scene.setWaypoint(x,y);renderFullMap();}
function drawPerson(scene, key, shirt, skin, hair) { const g = scene.make.graphics({ add: false }); g.fillStyle(0x101923).fillEllipse(2, 43, 34, 8); g.fillStyle(hair).fillRect(7, 1, 21, 8).fillRect(4, 7, 27, 8); g.fillStyle(skin).fillRect(7, 12, 21, 14); g.fillStyle(0x17293b).fillRect(10, 17, 3, 3).fillRect(22, 17, 3, 3); g.fillStyle(shirt).fillRect(5, 26, 25, 16); g.fillStyle(0xf5e5c0).fillRect(15, 29, 6, 10); g.fillStyle(0x27354d).fillRect(7, 40, 8, 8).fillRect(21, 40, 8, 8); g.generateTexture(key, 36, 48); g.destroy(); }
function createPlayerSprites(scene) {
  const source = scene.textures.get('player-source').getSourceImage(), sourceColumns = [8, 25, 42];
  [['male',[42,76,110]],['female',[316,350,384]]].forEach(([gender,sourceRows])=>{const sheet=document.createElement('canvas');sheet.width=48;sheet.height=96;const context=sheet.getContext('2d',{willReadFrequently:true});context.imageSmoothingEnabled=false;sourceRows.forEach((sourceY,row)=>sourceColumns.forEach((sourceX,column)=>context.drawImage(source,sourceX,sourceY,16,32,column*16,row*32,16,32)));for(let row=0;row<3;row+=1)for(let column=0;column<3;column+=1){const frame=context.getImageData(column*16,row*32,16,32);removeSpriteSheetBackground(frame.data,16,32);context.putImageData(frame,column*16,row*32);}const key=`player-${gender}`,texture=scene.textures.addCanvas(key,sheet);['down','up','side'].forEach((direction,row)=>[0,1,2].forEach((frame)=>texture.add(`${direction}-${frame}`,0,frame*16,row*32,16,32)));['down','up','side'].forEach((direction)=>scene.anims.create({key:`${gender}-walk-${direction}`,frames:[0,1,2].map((frame)=>({key,frame:`${direction}-${frame}`})),frameRate:8,repeat:-1}));});
  [['male',[42,76,110,144]],['female',[316,350,384,418]]].forEach(([gender,bikeRows])=>{const bikeSheet=document.createElement('canvas');bikeSheet.width=96;bikeSheet.height=128;const bikeContext=bikeSheet.getContext('2d',{willReadFrequently:true});bikeContext.imageSmoothingEnabled=false;const bikeColumns=[128,162,196];bikeRows.forEach((sourceY,row)=>bikeColumns.forEach((sourceX,column)=>bikeContext.drawImage(source,sourceX,sourceY,32,32,column*32,row*32,32,32)));for(let row=0;row<4;row+=1)for(let column=0;column<3;column+=1){const frame=bikeContext.getImageData(column*32,row*32,32,32);removeSpriteSheetBackground(frame.data,32,32);bikeContext.putImageData(frame,column*32,row*32);}const key=`bike-${gender}`,bikeTexture=scene.textures.addCanvas(key,bikeSheet);['down','up','left','right'].forEach((direction,row)=>[0,1,2].forEach((frame)=>bikeTexture.add(`${direction}-${frame}`,0,frame*32,row*32,32,32)));['down','up','left','right'].forEach((direction)=>scene.anims.create({key:`${gender}-bike-${direction}`,frames:[0,1,2].map((frame)=>({key,frame:`${direction}-${frame}`})),frameRate:12,repeat:-1}));});
}

class CampusScene extends Phaser.Scene {
  constructor() { super('campus'); }
  preload() { const [x,y]=state.savedPosition||[SPAWN.x,SPAWN.y];this.initialTile=`r${y<TILE_SIZE?1:2}_c${x<TILE_SIZE?1:2}`;this.load.image(this.initialTile,`assets/pixel_map/${this.initialTile}.webp`);this.load.json('map-data', 'assets/pixel_map/master.json');this.load.image('player-source','assets/Game Boy Advance - Pokemon FireRed _ LeafGreen - Playable Characters - Player Sprites.png');this.load.on('progress',(value)=>{el('load-status').textContent=`Preparing starting area… ${Math.round(value*100)}%`;});this.load.once('loaderror',()=>{el('load-status').textContent='A map file failed to load · reload to retry';}); }
  create() {
    const mapData = this.cache.json.get('map-data'); applyMapData(mapData); renderDex(); this.addMapTile(mapData.tiles.find(({id})=>id===this.initialTile)); this.buildWalkability(mapData);
    this.routeUnderlay = this.add.graphics().setDepth(4); this.routeLine = this.add.graphics().setDepth(5); this.targetMarker = this.add.graphics().setDepth(8); const labels = [];
    landmarks.forEach((item) => {
      const access = this.nearestWorld(item.x, item.y); item.accessIndex = access.index; item.accessX = access.x; item.accessY = access.y;
      item.labels.forEach(([x, y]) => { const label = this.add.text(x, y, `${item.letter} · ${item.shortName}`, { fontFamily: '"Press Start 2P"', fontSize: '15px', color: '#fff8d8', backgroundColor: '#17293be8', padding: { x: 8, y: 6 }, stroke: '#17293b', strokeThickness: 2 }).setOrigin(.5).setDepth(41); labels.push(label); });
      const marker = this.add.circle(item.accessX, item.accessY - 18, 7, 0xffe470).setDepth(40); this.tweens.add({ targets: marker, alpha: .25, scale: 1.7, duration: 650, yoyo: true, repeat: -1 });
    });
    createPlayerSprites(this); const spawn = this.nearestWorld(...(state.savedPosition||[SPAWN.x,SPAWN.y])); this.playerShadow = this.add.ellipse(spawn.x, spawn.y + 3, 60, 17, 0x101b2a, .35).setDepth(17); this.player = this.add.sprite(spawn.x, spawn.y, state.biking?`bike-${state.gender}`:`player-${state.gender}`, 'down-1').setOrigin(.5,1).setScale(3.2).setDepth(20); this.playerDot = this.add.circle(spawn.x, spawn.y, 26, 0x75deef, .25).setStrokeStyle(6, 0xffffff, .9).setDepth(18);
    npcs.forEach((npc, index) => { const point = this.nearestWorld(...npc.near); npc.x = point.x; npc.y = point.y; drawPerson(this, `npc-${index}`, npc.color, npc.skin, npc.hair); const sprite = this.add.sprite(npc.x + 38, npc.y - 12, `npc-${index}`).setScale(1.9).setDepth(19); this.tweens.add({ targets: sprite, y: sprite.y - 5, duration: 720 + index * 40, yoyo: true, repeat: -1, ease: 'Sine.easeInOut' }); const mark = this.add.text(sprite.x, sprite.y - 53, '!', { fontFamily: '"Press Start 2P"', fontSize: '18px', color: '#fff7ba', stroke: '#192c3d', strokeThickness: 6 }).setOrigin(.5).setDepth(20); this.tweens.add({ targets: mark, y: mark.y - 4, duration: 520, yoyo: true, repeat: -1 }); });
    this.cameras.main.setBounds(0, 0, WORLD_SIZE, WORLD_SIZE).startFollow(this.player, true, .16, .16).setRoundPixels(true).ignore(this.playerDot); this.mini = this.cameras.add().setName('minimap').setBackgroundColor(0x17293b).startFollow(this.player, true, 1, 1).setRoundPixels(true); this.mini.ignore(labels);
    state.scene = this; state.player = this.player; state.keys = this.input.keyboard.addKeys({ up: 'UP', down: 'DOWN', left: 'LEFT', right: 'RIGHT', w: 'W', a: 'A', s: 'S', d: 'D' }, false); this.layout(); this.scale.on('resize', () => this.layout());syncRemote();
    el('profile-submit').disabled=false;el('profile-submit').innerHTML='ENTER CAMPUS <span>→</span>';el('load-status').textContent='In Gate ready · full campus continues loading';this.loadRemainingTiles(mapData);if(state.profiled||state.startRequested)startGame();
    this.input.keyboard.on('keydown-E', gameShortcut(interact)); this.input.keyboard.on('keydown-M', gameShortcut(() => this.openDex())); this.input.keyboard.on('keydown-ESC', closePanels); this.input.keyboard.on('keydown-SPACE', gameShortcut(interact));
  }
  addMapTile(tile){if(!tile||this.mapTiles?.has(tile.id))return;(this.mapTiles??=new Set()).add(tile.id);this.add.image(...tile.global_offset,tile.id).setOrigin(0).setDisplaySize(TILE_SIZE,TILE_SIZE).setDepth(0);mapView.overview=null;}
  loadRemainingTiles(data){const remaining=data.tiles.filter(({id})=>id!==this.initialTile);remaining.forEach((tile)=>{this.load.image(tile.id,`assets/pixel_map/${tile.id}.webp`);this.load.once(`filecomplete-image-${tile.id}`,()=>this.addMapTile(tile));});this.load.image('canopy-overlay','assets/pixel_map/canopy-overlay.png');this.load.once('filecomplete-image-canopy-overlay',()=>this.add.image(0,0,'canopy-overlay').setOrigin(0).setDisplaySize(WORLD_SIZE,WORLD_SIZE).setDepth(30));this.load.once('complete',()=>{el('load-status').textContent='Full campus ready';});this.load.start();}
  buildWalkability(data) {
    this.walkable = new Uint8Array(GRID_SIZE * GRID_SIZE); data.walkability.rows.forEach((runs,y)=>runs.forEach(([x,length])=>this.walkable.fill(1,y*GRID_SIZE+x,y*GRID_SIZE+x+length)));
  }
  nearestWorld(x, y) { const index = nearestWalkable(this.walkable, GRID_SIZE, Math.floor(x / CELL_SIZE), Math.floor(y / CELL_SIZE)); return { index, x: (index % GRID_SIZE) * CELL_SIZE + CELL_SIZE / 2, y: Math.floor(index / GRID_SIZE) * CELL_SIZE + CELL_SIZE / 2 }; }
  canStand(x, y) { const gridX = Math.floor(x / CELL_SIZE), gridY = Math.floor(y / CELL_SIZE); return gridX >= 0 && gridY >= 0 && gridX < GRID_SIZE && gridY < GRID_SIZE && Boolean(this.walkable[gridY * GRID_SIZE + gridX]); }
  openDex() { openPanel('dex-panel'); renderDex(); }
  drawRoute() {
    if(!this.routePath?.length)return;const points=[[this.player.x,this.player.y],...this.routePath];this.routeUnderlay.clear().lineStyle(25,0x17293b,.72).beginPath().moveTo(...points[0]);points.slice(1).forEach(([x,y])=>this.routeUnderlay.lineTo(x,y));this.routeUnderlay.strokePath();this.routeLine.clear().lineStyle(10,0xffdb4d,1).beginPath().moveTo(...points[0]);points.slice(1).forEach(([x,y])=>this.routeLine.lineTo(x,y));this.routeLine.strokePath();
  }
  setRoute(item,silent=false) {
    if(item.accessIndex==null){const access=this.nearestWorld(item.x,item.y);item.accessIndex=access.index;item.accessX=access.x;item.accessY=access.y;}const start=this.nearestWorld(this.player.x,this.player.y).index,path=findGridPath(this.walkable,GRID_SIZE,start,item.accessIndex);if(!path.length){if(!silent)showToast('No walkable route found.');return;}this.routePath=path.map((index)=>[(index%GRID_SIZE)*CELL_SIZE+4,Math.floor(index/GRID_SIZE)*CELL_SIZE+4]);this.routeOrigin={x:this.player.x,y:this.player.y};this.lastReroute=performance.now();this.drawRoute();this.targetMarker.clear().lineStyle(8,0xffffff,1).strokeCircle(item.accessX,item.accessY,36).fillStyle(0xf06955,.95).fillCircle(item.accessX,item.accessY,23);state.target=item;if(!silent){el('route-name').textContent=item.shortName;el('route-chip').hidden=false;el('dex-panel').close();renderDex();showToast(`Route set: ${item.name}`);playTone(590,.08);}
  }
  setWaypoint(x,y) { const access=this.nearestWorld(x,y),waypoint={id:'custom-waypoint',name:'Custom waypoint',shortName:'WAYPOINT',x,y,accessIndex:access.index,accessX:access.x,accessY:access.y};this.setRoute(waypoint); }
  refreshRoute(time) { if(!state.target)return;if(Math.hypot(this.player.x-state.target.accessX,this.player.y-state.target.accessY)<55){showToast('You have arrived!');playTone(760,.12);this.clearRoute();return;}if(time>(this.nextRouteCheck||0)){this.nextRouteCheck=time+250;this.routePath=trimPathToPlayer(this.routePath,this.player.x,this.player.y);if(distanceToPath(this.player.x,this.player.y,this.routePath)>110)this.setRoute(state.target,true);}if(time>(this.nextRouteDraw||0)){this.nextRouteDraw=time+100;this.drawRoute();} }
  clearRoute() { this.routeUnderlay.clear(); this.routeLine.clear(); this.targetMarker.clear(); this.routePath=null; state.target = null; el('route-chip').hidden = true; renderDex(); }
  layout() {
    const width = this.scale.width, height = this.scale.height, mobile = width < 760; this.cameras.main.setZoom(cameraZoom(this));
    const size = mobile ? Math.min(174, width * .44) : 240, x = mobile ? width - size - 12 : 24, y = mobile ? 100 : height - size - 24; this.mini.setViewport(x, y, size, size).setZoom(mobile ? .18 : .16);
    this.miniMaskGraphic?.destroy(); this.miniMaskGraphic = this.make.graphics({ add: false }).fillStyle(0xffffff).fillCircle(x + size / 2, y + size / 2, size / 2 - 4); this.mini.setMask(this.miniMaskGraphic.createGeometryMask()); document.documentElement.style.setProperty('--mini-x', `${x}px`); document.documentElement.style.setProperty('--mini-y', `${y}px`); document.documentElement.style.setProperty('--mini-size', `${size}px`); document.documentElement.style.setProperty('--route-y', `${mobile ? y + size + 8 : y - 58}px`);
  }
  update(time, delta) {
    if (!state.started || !this.player || document.querySelector('dialog[open]')) return; const k = state.keys, left = k.left.isDown || k.a.isDown || state.touch.has('left'), right = k.right.isDown || k.d.isDown || state.touch.has('right'), up = k.up.isDown || k.w.isDown || state.touch.has('up'), down = k.down.isDown || k.s.isDown || state.touch.has('down'); let dx = (right ? 1 : 0) - (left ? 1 : 0), dy = (down ? 1 : 0) - (up ? 1 : 0); if (dx && dy) { dx *= .707; dy *= .707; }
    if(mapIsOpen()){panFullMap(dx,dy,Math.min(delta,40));renderFullMap(time);return;}
    const step = (state.biking ? 600 : 300) * Math.min(delta, 40) / 1000, slices = movementSlices(step); for (let slice=0;slice<slices;slice+=1) { const targetX = this.player.x + dx * step/slices, targetY = this.player.y + dy * step/slices; if (this.canStand(targetX, targetY)) this.player.setPosition(targetX, targetY); else if (this.canStand(targetX, this.player.y)) this.player.x = targetX; else if (this.canStand(this.player.x, targetY)) this.player.y = targetY; }
    if (dx || dy) { const direction = Math.abs(dx) > Math.abs(dy) ? (state.biking ? (dx < 0 ? 'left' : 'right') : 'side') : dy < 0 ? 'up' : 'down'; this.player.setFlipX(!state.biking && direction === 'side' && dx > 0); this.player.anims.play(`${state.gender}-${state.biking?'bike':'walk'}-${direction}`, true); if(time>(this.nextSave||0)){save();this.nextSave=time+750;} } else this.player.anims.stop(); this.playerShadow.setPosition(this.player.x, this.player.y + 3); this.playerDot.setPosition(this.player.x, this.player.y); this.refreshRoute(time); if(time>(this.nextHud||0)){this.nextHud=time+100;updateHud();}
  }
}
function closePanels() { document.querySelectorAll('.panel[open]').forEach((panel) => panel.close()); document.body.classList.remove('map-open'); setControlMode(false); }
function boot() { loadSave();el('profile-screen').hidden=state.profiled;renderDex();const touchUI=matchMedia('(pointer:coarse), (max-width:760px)').matches;el('hint-key').textContent=touchUI?'A':'E';el('sound-button').textContent=state.muted?'×':'♫';el('bike-button').textContent=state.biking?'WALK':'BIKE';el('bike-button').setAttribute('aria-pressed',state.biking);new Phaser.Game({ type: Phaser.AUTO, parent: 'game', width: window.innerWidth, height: window.innerHeight, backgroundColor: '#68b733', pixelArt: true, scale: { mode: Phaser.Scale.RESIZE }, scene: CampusScene }); }
function startGame(){if(!state.scene){state.startRequested=true;el('load-status').textContent='Entering as soon as In Gate is ready…';return;}if(state.started)return;state.started=true;state.startRequested=false;playTone(520,.12);startTutorial();}
el('tutorial-next').addEventListener('click',()=>showTutorialStep(tutorialStep+1));el('tutorial-skip').addEventListener('click',finishTutorial);el('help-button').addEventListener('click',()=>startTutorial(true));el('dex-button').addEventListener('click', () => state.scene?.openDex()); el('map-button').addEventListener('click', () => mapIsOpen()?zoomFullMap(.8):state.scene?.openDex()); el('sound-button').addEventListener('click', () => { state.muted = !state.muted; el('sound-button').textContent = state.muted ? '×' : '♫'; save(); }); el('action-button').addEventListener('click', () => mapIsOpen()?zoomFullMap(1.25):interact()); el('clear-route').addEventListener('click', () => state.scene?.clearRoute()); document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => el(button.dataset.close).close()));document.querySelectorAll('.panel').forEach((panel)=>panel.addEventListener('close',()=>{if(panel.id==='map-panel'){document.body.classList.remove('map-open');setControlMode(false);}}));
el('coffee-button').addEventListener('click',()=>openPanel('support-panel'));el('copy-iban').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('PK50NAYA1234503000856955');showToast('IBAN copied!');}catch{showToast('Could not copy—select the IBAN manually.');}});
el('profile-form').addEventListener('submit',(event)=>{event.preventDefault();const data=new FormData(event.currentTarget),email=String(data.get('email')||'').trim().toLowerCase(),gender=String(data.get('gender')||'');if(!event.currentTarget.reportValidity()||!validGender(gender))return;state.profiled=true;state.email=email;state.gender=gender;syncRemote();el('profile-screen').hidden=true;if(state.player&&!state.biking)state.player.setTexture(`player-${gender}`,'down-1');startGame();});
el('bike-button').addEventListener('click', () => { state.biking = !state.biking; el('bike-button').setAttribute('aria-pressed', state.biking); el('bike-button').textContent = state.biking ? 'WALK' : 'BIKE'; if(state.scene){state.scene.cameras.main.zoomTo(cameraZoom(state.scene),280,'Sine.easeOut');state.player.setFlipX(false).setTexture(state.biking?`bike-${state.gender}`:`player-${state.gender}`,'down-1');} save();showToast(state.biking?'Bike mode: faster travel!':'Walking mode'); playTone(state.biking?700:480,.08); });
el('minimap-button').addEventListener('click',openFullMap);
el('full-map').addEventListener('pointerup',setMapWaypoint);
window.addEventListener('resize',()=>{if(mapIsOpen())resizeFullMap();});
window.addEventListener('pagehide',save);
const touchPointers=new Map(),syncTouch=()=>{state.touch.clear();touchPointers.forEach((direction)=>{if(direction)state.touch.add(direction);});document.querySelectorAll('[data-direction]').forEach((button)=>button.classList.toggle('pressed',state.touch.has(button.dataset.direction)));};document.querySelectorAll('[data-direction]').forEach((button)=>{button.addEventListener('pointerdown',(event)=>{event.preventDefault();button.setPointerCapture?.(event.pointerId);touchPointers.set(event.pointerId,button.dataset.direction);syncTouch();navigator.vibrate?.(8);});button.addEventListener('pointermove',(event)=>{if(!touchPointers.has(event.pointerId))return;const next=document.elementFromPoint(event.clientX,event.clientY)?.closest?.('[data-direction]');touchPointers.set(event.pointerId,next?.dataset.direction||null);syncTouch();});['pointerup','pointercancel','lostpointercapture'].forEach((name)=>button.addEventListener(name,(event)=>{touchPointers.delete(event.pointerId);syncTouch();}));});document.querySelectorAll('.game-button').forEach((button)=>{button.addEventListener('pointerdown',()=>{button.classList.add('pressed');navigator.vibrate?.(10);});['pointerup','pointercancel','pointerleave'].forEach((name)=>button.addEventListener(name,()=>button.classList.remove('pressed')));});const clearTouch=()=>{touchPointers.clear();state.touch.clear();document.querySelectorAll('.pressed').forEach((button)=>button.classList.remove('pressed'));};window.addEventListener('blur',clearTouch);document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTouch();});document.querySelector('.mobile-controls').addEventListener('contextmenu',(event)=>event.preventDefault());
boot();
